import type { Metadata } from "next";
import "@/styles/global.css";
import NotesProvider from "@/context/NotesProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<NotesProvider>{children}</NotesProvider>
			</body>
		</html>
	);
}
