// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
	/**
	 * Detail
	 */
	detail?: Array<ValidationError>;
};

/**
 * NoteCreate
 * Schema for creating a new note.
 */
export type NoteCreate = {
	/**
	 * Title
	 * Note title
	 */
	title: string;
	/**
	 * Content
	 * Lexical JSON content
	 */
	content: {
		[key: string]: unknown;
	};
};

/**
 * NoteResponse
 * Schema for note responses.
 */
export type NoteResponse = {
	/**
	 * Title
	 * Note title
	 */
	title: string;
	/**
	 * Content
	 * Lexical JSON content
	 */
	content: {
		[key: string]: unknown;
	};
	/**
	 * Id
	 */
	id: number;
	/**
	 * Created At
	 */
	created_at: string;
	/**
	 * Updated At
	 */
	updated_at: string;
};

/**
 * NoteUpdate
 * Schema for updating an existing note.
 */
export type NoteUpdate = {
	/**
	 * Title
	 * Note title
	 */
	title: string;
	/**
	 * Content
	 * Lexical JSON content
	 */
	content: {
		[key: string]: unknown;
	};
};

/**
 * NotesListResponse
 * Schema for notes list response.
 */
export type NotesListResponse = {
	/**
	 * Notes
	 */
	notes: Array<NoteResponse>;
	/**
	 * Total
	 */
	total: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
	/**
	 * Location
	 */
	loc: Array<string | number>;
	/**
	 * Message
	 */
	msg: string;
	/**
	 * Error Type
	 */
	type: string;
};

export type GetNotesApiNotesGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/api/notes/";
};

export type GetNotesApiNotesGetResponses = {
	/**
	 * Successful Response
	 */
	200: NotesListResponse;
};

export type GetNotesApiNotesGetResponse =
	GetNotesApiNotesGetResponses[keyof GetNotesApiNotesGetResponses];

export type CreateNoteApiNotesPostData = {
	body: NoteCreate;
	path?: never;
	query?: never;
	url: "/api/notes/";
};

export type CreateNoteApiNotesPostErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type CreateNoteApiNotesPostError =
	CreateNoteApiNotesPostErrors[keyof CreateNoteApiNotesPostErrors];

export type CreateNoteApiNotesPostResponses = {
	/**
	 * Successful Response
	 */
	201: NoteResponse;
};

export type CreateNoteApiNotesPostResponse =
	CreateNoteApiNotesPostResponses[keyof CreateNoteApiNotesPostResponses];

export type DeleteNoteApiNotesNoteIdDeleteData = {
	body?: never;
	path: {
		/**
		 * Note Id
		 */
		note_id: number;
	};
	query?: never;
	url: "/api/notes/{note_id}";
};

export type DeleteNoteApiNotesNoteIdDeleteErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type DeleteNoteApiNotesNoteIdDeleteError =
	DeleteNoteApiNotesNoteIdDeleteErrors[keyof DeleteNoteApiNotesNoteIdDeleteErrors];

export type DeleteNoteApiNotesNoteIdDeleteResponses = {
	/**
	 * Successful Response
	 */
	204: void;
};

export type DeleteNoteApiNotesNoteIdDeleteResponse =
	DeleteNoteApiNotesNoteIdDeleteResponses[keyof DeleteNoteApiNotesNoteIdDeleteResponses];

export type UpdateNoteApiNotesNoteIdPutData = {
	body: NoteUpdate;
	path: {
		/**
		 * Note Id
		 */
		note_id: number;
	};
	query?: never;
	url: "/api/notes/{note_id}";
};

export type UpdateNoteApiNotesNoteIdPutErrors = {
	/**
	 * Validation Error
	 */
	422: HttpValidationError;
};

export type UpdateNoteApiNotesNoteIdPutError =
	UpdateNoteApiNotesNoteIdPutErrors[keyof UpdateNoteApiNotesNoteIdPutErrors];

export type UpdateNoteApiNotesNoteIdPutResponses = {
	/**
	 * Successful Response
	 */
	200: NoteResponse;
};

export type UpdateNoteApiNotesNoteIdPutResponse =
	UpdateNoteApiNotesNoteIdPutResponses[keyof UpdateNoteApiNotesNoteIdPutResponses];

export type RootGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/";
};

export type RootGetResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type HealthCheckHealthGetData = {
	body?: never;
	path?: never;
	query?: never;
	url: "/health";
};

export type HealthCheckHealthGetResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type ClientOptions = {
	baseURL: "http://localhost:8000" | (string & {});
};
